import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Anek_Bangla, Inter } from "next/font/google";
import "./globals.css";

const anek_bangla = Anek_Bangla({
  subsets: ["latin"],
  variable: "--anek-bangla",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, anek_bangla.variable)}>
        {children}
      </body>
    </html>
  );
}
